/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Pedidos;

/**
 *
 * @author Renato
 */
public class TelaNovoPedido extends javax.swing.JInternalFrame {
  TelaJtable telaJtable;
    public TelaNovoPedido() {
        initComponents();
        //Array para conter os itens do ComboBox
         ArrayList<String> itens = new ArrayList<>();
         
        //Laço para contar de 1 a 50.
        for (int i = 1; i < 51; i++) {
            
            //Adicionando 50 vezes a palvra Camapanha concatenado com o i e adicionando ao arrays.
              itens.add(" Campanha " +i);
        }
        
        //Laço que percorre o array itens e adiciona ao ComboBox.
        for (int i = 0; i < itens.size(); i++) {
            
            //Adicionando ao combobox.
            jComboListas.addItem(itens.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnConfirmarCampanha = new javax.swing.JButton();
        jComboListas = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel1.setText("Insira o numero da campanha");

        btnFechar.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        btnFechar.setText("  Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnConfirmarCampanha.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        btnConfirmarCampanha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/check-square.png"))); // NOI18N
        btnConfirmarCampanha.setText("  Confirmar");
        btnConfirmarCampanha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCampanhaActionPerformed(evt);
            }
        });

        jComboListas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboListas, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboListas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        //Fechando tela.
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnConfirmarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCampanhaActionPerformed
        //Instanciando Class pedidos
        Pedidos pedidos = new Pedidos();
        
        //Pegando o item slecionado no ComboBox.
        String selected = (String) jComboListas.getSelectedItem();
        
        //Tirando espaços contidos no inicio e fim da variavel.
        selected = selected.trim();
      
         
       //Menssagem de confirmção do numero da camapanha        
        JOptionPane.showMessageDialog(null,"Deseja colocar pedido na campanha: "+selected+" ?");
       

        //Verificando se a telaJtable não foi istanciada.
         if (telaJtable == null) {
            telaJtable = new TelaJtable();
        }
        //Setando Jtable como visivel.
        telaJtable.setVisible(true);
        //Passando o item selecionado para o metodo contido na class TelaJtable.
        telaJtable.recebeNuemPedido(selected);
       
       //Chamando tela que conte jtable com a tebela pra pedidos
        Desktop.JMenuDesktop.add(telaJtable);
        
        this.dispose();
      
    }//GEN-LAST:event_btnConfirmarCampanhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarCampanha;
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox<String> jComboListas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
